service: api-users
frameworkVersion: "3"

params:
  dev:
    salt: 9b3770814adbe509afcaf65e974f84309097c945
    jwtSecret: #putyourjwtsecrethere

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SALT: ${param:salt}
    JWT_SECRET: ${param:jwtSecret}

functions:
  createUser:
    handler: /application/api/createUser.handler
    events:
      - httpApi:
          path: /api/user
          method: post
  loginUser:
    handler: /application/api/loginUser.handler
    events:
      - httpApi:
          path: /api/user/login
          method: post

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

plugins:
  - serverless-offline
