service: api-users
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: "${opt:stage, 'dev'}"
  logs:
    httpApi: true
  environment: ${file(env-${self:provider.stage}.yml)}

functions:
  createUser:
    handler: /application/api/createUser.handler
    events:
      - httpApi:
          path: /api/user
          method: post
  signInUser:
    handler: /application/api/signInUser.handler
    events:
      - httpApi:
          path: /api/user/signin
          method: post
custom:
  serverless-offline:
    host: 0.0.0.0 # for docker container hosting
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

plugins:
  - serverless-offline
